language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "cram-inc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: cram-inc
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: jfGIYmjmv88ZZdY3UviaGbAVngG6gFn6V2hIVPM5OXM51IyxGihykdtK3S7u0bQCEiCHfRvBidy3LIEiV5FErdTXVUmY5sfOIMQ457i8BR7TExNMZ2tAXMJ1pgoTnuvmDcVP0q6FD7ALwTz4pqTXCJrR0u/XYJUenXaarZQzbQirwdxK49V0ifbYDOuputzFiWrBuZYq5o2OsNk91VPbdDz3Ak8lC1gRXBJmLmlQeUk6ugx+V96B3czMOm87cGXWySRViSmH3j5K5tOzuMknONNaZpeb1GVeA32Hg7oTq0oYjCD88YYasAa91CEe7yRu5dzNViRHsbabUqGfdAmUpaHmm9yYViPSt5/1KDDqJNfZW1sFSZD8xb/MMdXQVSUnjc7b5r5rgpwsSRCUWEfpqTa8XgyC4S7JYc5REEF0ay3EMqrx+F6NT5Z0hPZstDZuBs88NEqx/TqRJCrNd/Q4QeJ+7a/7wzXZRWdXeSvhH4+bT6GvfD2cc2Q8IcLPsgTY4WYvcPlidAOZ4JvU16iZJatKntU+oPzGYYi3/xLmHoJ3zQLrwbPkVJSrWBvumIqFAqC4NGFg4UOlnB5CSMQuQ8MDwjx3MQF1RsNaJhhJ+JvR8j835jbDx4oIIuklD601NgsXEumFDkeFmYlzr3kWkejee8lYOsWLzV0+jOwByJ0=
