language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "cram-inc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
<<<<<<< HEAD
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: cram-inc
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: KLTFnizrKEKbiiyypmC8gbfHEc9t7LzhhefDVk9W7zll9MpPx6IiohK9uCy9CX296MjBbfr0Gsyaay/gMfWdXmRozfjtQcLui9B5tjc091pr+Qug/bozMVO/edIWLGKTj/Bz8A2arSGtJpeYcoJwowz7OUR9ngsUpA7MDWozU2Tq3K3zbTdZQDYm4wnQp0tBzNn9d3IHis4KWT5fqBzFcTxY+mh+jxr4F9W1223nTIgg5F9+R2eelIQUBL0kdmh2kjuDz4Ku88VgUxErWAM5151DsFcQkl9dy/QpbMCMoHX9qvw8EaWRjl8V7ZjSzI86X0YQdVcA8zo1fRu0o00MtBiMnIQgja4woVluy3tQ6aUbGHcD34TvmPTv/iinyQ2jWd9a1EyZRjfux/JX/fUpltxvMqIMFmOcIT6KlkAJ8o3yLvG3hI+A/xOJCmoDvod8xf+cCWVjMU6fhAwCVPGniJMCvPwwQk/grx1q7S66rk7PE/llAs5sSGqbX2VfwRlV9+atMyjvtVCsUhGkaCqa95grPjs7Ltoe5SioX2KV4Vi7RBAsmMX3Dn99Pei+a7yHaQAZYfsB7zePxIuQ+2WG5HFxMkyb3lqWvltNWP3YD3i1cGE1RTcvpYE8naBVKp4+AIztbS9N0XR0Cg6et76dFXmhRBQhx9tG5xONrZ7+4Jo=
